apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pvc-7af91bf5-cd7f-4717-a3ab-5b1d16a0abf9
    fsType: ext4
